name: Trigger auto deployment for invoicingportfolioproject

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/invoicingportfolioproject-AutoDeployTrigger-d59f341d-5aa9-4339-a54e-ddeab1a465b5.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.INVOICINGPORTFOLIOPROJECT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.INVOICINGPORTFOLIOPROJECT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.INVOICINGPORTFOLIOPROJECT_AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: invoicingportfolioproject
          resourceGroup: InvoicingPortfolioProject
          imageToDeploy: ghcr.io/verbeekenico/incognico-invoicing:latest


